### ISSUE TITLE
OneBody Mobile App

### ISSUE THREAD

**Issue by hunternet93** [seven1m/onebody#695]
This is a tracking issue for work on an Android / iOS app for OneBody. The app itself is in [this repo](https://github.com/churchio/onebody-mobile), this issue is to track the OneBody changes needed to allow the app to work.

The app will use [Apache Cordova](http://cordova.apache.org/) to create an app wrapper that simply loads a OneBody instance in an in-app browser. It will also support push notifications via the new API.

### Current status
* [A skeleton of the app has been created](https://github.com/churchio/onebody-mobile).
* @seven1m is finishing up work on [the API](https://github.com/churchio/onebody/pull/650/).

### Todo
* Implement push notifications by polling the new API
* Alter the mobile user interface slightly for better user experience:
    * Make the header navbar fixed.
    * Make OneBody-styled error pages (i.e. 404 on bad links)

**Comment by seven1m** [comment]
Closing this for now. If there is renewed interest in it, we can reopen.
