### ISSUE TITLE
security risk

### ISSUE THREAD

**Issue by masukomi** [seven1m/onebody#700]
in your app.yml it says 

` sudo: ['ALL=(ALL) NOPASSWD:ALL']`

if that is actually editing the sudoers file then i think you've opened up a _huge_ security hole in that anyone can now become root without needing a password.

**Comment by seven1m** [comment]
I think it might be possible to reduce that. I’ll see what I can do. 

To be clear though, a user would still need to log into the machine. The installer assumes you are not creating other users on your Digital Ocean vps instance.
