### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by dwainehohne** [seven1m/onebody#703]
When importing people into the directory, I get to the page where you define the fields from the CSV file, and when clicking "Save & Continue" I am met with an error saying:

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

This error comes up even if I select the option to skip preview. 
![screen shot 2018-01-17 at 15 08 38](https://user-images.githubusercontent.com/34269465/35044388-e2608d8e-fb98-11e7-9737-9a7343628137.png)

**Comment by seven1m** [comment]
I believe this is fixed on the latest master branch. Next release will have it fixed, and the nightly package already does.
