### ISSUE TITLE
Vagrant install not working

### ISSUE THREAD

**Issue by seanfcarroll** [seven1m/onebody#704]
Awesome project! This is a really inspiring app.
I tried the quick start install using Vagrant, but I am getting errors. Thanks for any comments on how to fix this.

<img width="986" alt="screen shot 2018-03-18 at 16 01 49" src="https://user-images.githubusercontent.com/11340230/37567333-dbf7b83a-2ac5-11e8-95dd-ea5fa67fdef8.png">

**Comment by arvychile** [comment]
Hii, I'm having same exact problem. Any pointers on howto fix this?

**Comment by seven1m** [comment]
This is fixed in 810e96bbf9bee4a2e0dd025b2d4be62a4711f1e7
