### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by Nomisdk** [seven1m/onebody#706]
Hi

I get this message when i go to the Admin module.
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

I have downloaded and setup the Virtual OVF package and set it up 2 days ago, and have testing it a little bit.

How do i fix this error?

**Comment by itsbm** [comment]
Same problem here, just started a couple days ago with no changes on my end.
apache error.log below

App 1946 stderr: Started GET "/admin" for xxx.xxx.xxx.xxx at 2018-09-26 17:36:18 -0700
App 1946 stderr: Processing by Administration::DashboardsController#show as HTML
App 1946 stderr:   Rendered administration/dashboards/show.html.haml within layouts/default (292.4ms)
App 1946 stderr: Completed 500 Internal Server Error in 389ms (ActiveRecord: 75.8ms)
App 1946 stderr:
App 1946 stderr: ActionView::Template::Error (no implicit conversion of String into Integer):
App 1946 stderr:      5:
App 1946 stderr:      6: = tls_warning
App 1946 stderr:      7:
App 1946 stderr:      8: - unless OneBody.up_to_date?
App 1946 stderr:      9:   .alert.alert-info
App 1946 stderr:     10:     %h4
App 1946 stderr:     11:       = icon 'fa fa-info-circle'
App 1946 stderr:   lib/version_info.rb:23:in `[]'
App 1946 stderr:   lib/version_info.rb:23:in `block in latest_version'
App 1946 stderr:   lib/version_info.rb:22:in `latest_version'
App 1946 stderr:   lib/version_info.rb:31:in `up_to_date?'
App 1946 stderr:   app/views/administration/dashboards/show.html.haml:8:in `_app_views_administration_dashboards_show_html_haml___839465298323584009_69900331452260'
App 1946 stderr:

**Comment by seven1m** [comment]
I’m sprry guys. I’ll take a look at this today.

**Comment by seven1m** [comment]
Could you please try editing line 14 of `lib/version_info.rb` so that it looks like this:

```
  GITHUB_REPO_OWNER = 'seven1m'.freeze
```

Restart OneBody and see if the error goes away.

**Comment by seven1m** [comment]
This is fixed in the code on GitHub. I'll be making a new release shortly.

**Comment by seven1m** [comment]
I got the deb package builds working again (they were broken for awhile) and there is a new "nightly" deb package available that fixes this. Please [backup your db and files](https://github.com/seven1m/onebody/wiki/Backups) then update to the Nightly package by following the instructions here: https://github.com/seven1m/onebody/wiki/Install-Deb-Package-(Debian-and-Ubuntu)#nightly-packages-master-branch

**Comment by seven1m** [comment]
I just realized the new release will need a proper node.js installation on your server. This is new, as the old release didn't need it.

To install:

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install nodejs
```

**Comment by seven1m** [comment]
This will be fixed in the next release, which I am working on testing.

The fix is presently in the nightly package, in case you're feeling adventurous. Otherwise, 3.9.0 should be out shortly. Thanks!
