### ISSUE TITLE
emails.mime?

### ISSUE THREAD

**Issue by Nomisdk** [seven1m/onebody#707]
Hi

I have setup the integration to Mailgun, and sending email works fine.
But i cant seem to figure out how to recieve email?
I am following the guide at: https://github.com/seven1m/onebody/wiki/Mailgun-Email-Setup

I have added the " 0 	catch_all() 	forward("http://members.mychurch.com/emails.mime")"
(And changed the url to my own site)

But i dont seem to work.

When i browse to the /emails.mime it dont seem to exist and i get the error:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

I am using the Virtual Appliance.

**Comment by seven1m** [comment]
The URL only response to a POST request. I'm not sure why the Mailgun route wouldn't be working for you... 

If you run the following from a Linux terminal, do you see similar output?

```
curl -v -X POST http://members.mychurch.com/emails.mime 2>&1 | grep HTTP
> POST /emails.mime HTTP/1.1
< HTTP/1.1 201 Created
```
