### ISSUE TITLE
Changing other users information

### ISSUE THREAD

**Issue by Nomisdk** [seven1m/onebody#709]
Hi 

Not really a issue, but i cant seem to find any function where i as a Admin, can update/change users information.
Is that not possible?

**Comment by Mbd06b** [comment]
Select a person from the directory.
While looking at their profile. In the menu on the left. "Profile" will be
highlighted.
Click "Edit Profile", and you can edit any profile as an administrator.

Let me know if that works.

*Matthew Dowell*
mbd06b@gmail.com
(210) 386-2786
10046 Oakland Rd.
San Antonio, TX 78240

**Comment by seven1m** [comment]
That is the answer, thanks! I'm going to close this, but feel free to comment if you are still having trouble.
