### ISSUE TITLE
Cannot access admin page after updates

### ISSUE THREAD

**Issue by mhartel** [seven1m/onebody#711]
Hello -

I am running OneBody 3.8 on a digital ocean droplet.  I applied some ubuntu updates to the droplet on October 2nd.  Since applying those updates I am getting the following when trying to access the admin page via the browser.  

![image](https://user-images.githubusercontent.com/44347559/47271952-ae1a7380-d54c-11e8-96a7-811c7c37e16e.png)

Below are the updates (i believe) that caused the issue. 

![image](https://user-images.githubusercontent.com/44347559/47271944-9cd16700-d54c-11e8-8f6a-d660b6612758.png)

I'm not a skilled ubuntu user by any means, but is there some place where i can get some more detailed OneBody logging?  the site works fine for the users, but the admin console is completely down.

Thanks for your time - I appreciate the work you've put in to making this!

Matt

**Comment by seven1m** [comment]
@mhartel I’m sorry, this is a bug in the last released version. See 
https://github.com/seven1m/onebody/issues/706#issuecomment-425078947 for a quick fix. The next release will have this fix.

**Comment by mhartel** [comment]
@seven1m  Thanks for that update.  I'm sorry where is the file relative to root?  I'm having a bit of trouble navigating here.  Sorry I'm not a Linux admin ;)

**Comment by seven1m** [comment]
Try `/opt/onebody/lib/version_info.rb`

**Comment by mhartel** [comment]
Thank you Tim.  That worked great.  I even know how to use vi now!
