### ISSUE TITLE
Admin page not working

### ISSUE THREAD

**Issue by blikkies** [seven1m/onebody#712]
Hi Tim

Notices Admin page not working,  though it could be something wrong with my specific install,  I setup a new instance by have the same issue on new droplet.

Is there anything I need to do to fix this.

Thanks
Dave

**Comment by seven1m** [comment]
Please see solution on #711. Thanks!

**Comment by blikkies** [comment]
Sorted it, thanks,  neglected to look at closed issues.  thanks for quick reply.  

God Bless
Dave

**Comment by seven1m** [comment]
I’ll leave this issue open and try to get a release out today or tomorrow to fix.

**Comment by blikkies** [comment]
Hi Tim

Your a legend,  thanks from down under.

Was sad to see that you had to make the decision to close down Church.io <http://church.io/>.  Just to let you know if it was not for that collaboration I would not have stumbled across Onebody.  I am still in the process of getting church members used to the idea of the electronic directory functionality and private community that is Onebody.

I was part of the Slack community joined about a year ago,  and yes I am a user and have no reputable skill to assist in development,  but if there is anything I can do to help like document or test please let me know.

Thank-you again for this gift you have given the Christian community really appreciate it.

Kind regards and God Bless

Dave

**Comment by seven1m** [comment]
This was fixed by resurrecting the old GitHub org so the old URL still works. I'm working on the next release of OneBody, which should point that URL to the new repo URL.
