### ISSUE TITLE
Family phone # doesn't appear for all families in printed directory

### ISSUE THREAD

**Issue by ShoeBar** [seven1m/onebody#714]
We're checking all our congregation's listings in the printed directory, and not all families display the family phone number. In some cases, individual phone numbers appear, but this isn't always the case.
We've checked the sharing settings for our instance, and "home phone" is shown as being shared.
For what it's worth, we're using OneBody with the API to synch from PowerChurch.
Current printed directory is attached. Note family entries: Anderson, Biggers, Burkhardt.
[directory_20190131.pdf](https://github.com/seven1m/onebody/files/2818577/directory_20190131.pdf)

**Comment by seven1m** [comment]
This should be fixed in the latest version.
