### ISSUE TITLE
Error when running 'vagrant up'

### ISSUE THREAD

**Issue by loumarven** [seven1m/onebody#719]
**Issue**:
`vagrant up` not working

This is the error I get when I run `vagrant up`:
> Failed to restart thin.service: Unit thin.service not found.

**Root cause**:
Required(?) bundler version was not installed. Ran `vagrant provision` and got this error:
> Could not find 'bundler' (1.17.3) required by your /vagrant/Gemfile.lock.

**Solution**:

1. ssh into the vagrant box with `vagrant ssh`
2. run the command `sudo gem install bundler:1.17.3`
3. type `exit` to exit from the ssh session
4. run `vagrant provision`
5. run `vagrant up` again and visit http://localhost:3000

**Note**:
_Opened this issue in case others are experiencing the same and are looking for a solution_

**Comment by joshaidan** [comment]
See PR  #722. A fix for this is to edit Gemfile.lock, and change the last line at the bottom:

```
BUNDLED WITH
   1.17.3
```

to this:

```
BUNDLED WITH
    2.1.4
```
Rubygems seems to default to installing 2.1.4 now.
